#!/usr/bin/env bash
cat dictionary.js | awk '$1 ~ /^a/' > dictionaries/en/a.js
cat dictionary.js | awk '$1 ~ /^b/' > dictionaries/en/b.js
cat dictionary.js | awk '$1 ~ /^c/' > dictionaries/en/c.js
cat dictionary.js | awk '$1 ~ /^d/' > dictionaries/en/d.js
cat dictionary.js | awk '$1 ~ /^e/' > dictionaries/en/e.js
cat dictionary.js | awk '$1 ~ /^f/' > dictionaries/en/f.js
cat dictionary.js | awk '$1 ~ /^g/' > dictionaries/en/g.js
cat dictionary.js | awk '$1 ~ /^h/' > dictionaries/en/h.js
cat dictionary.js | awk '$1 ~ /^i/' > dictionaries/en/i.js
cat dictionary.js | awk '$1 ~ /^j/' > dictionaries/en/j.js
cat dictionary.js | awk '$1 ~ /^k/' > dictionaries/en/k.js
cat dictionary.js | awk '$1 ~ /^l/' > dictionaries/en/l.js
cat dictionary.js | awk '$1 ~ /^m/' > dictionaries/en/m.js
cat dictionary.js | awk '$1 ~ /^n/' > dictionaries/en/n.js
cat dictionary.js | awk '$1 ~ /^o/' > dictionaries/en/o.js
cat dictionary.js | awk '$1 ~ /^p/' > dictionaries/en/p.js
cat dictionary.js | awk '$1 ~ /^q/' > dictionaries/en/q.js
cat dictionary.js | awk '$1 ~ /^r/' > dictionaries/en/r.js
cat dictionary.js | awk '$1 ~ /^s/' > dictionaries/en/s.js
cat dictionary.js | awk '$1 ~ /^t/' > dictionaries/en/t.js
cat dictionary.js | awk '$1 ~ /^u/' > dictionaries/en/u.js
cat dictionary.js | awk '$1 ~ /^v/' > dictionaries/en/v.js
cat dictionary.js | awk '$1 ~ /^w/' > dictionaries/en/w.js
cat dictionary.js | awk '$1 ~ /^x/' > dictionaries/en/x.js
cat dictionary.js | awk '$1 ~ /^y/' > dictionaries/en/y.js
cat dictionary.js | awk '$1 ~ /^z/' > dictionaries/en/z.js

cat dictionary.js | awk '$1 ~ /^A/' >> dictionaries/en/a.js
cat dictionary.js | awk '$1 ~ /^B/' >> dictionaries/en/b.js
cat dictionary.js | awk '$1 ~ /^C/' >> dictionaries/en/c.js
cat dictionary.js | awk '$1 ~ /^D/' >> dictionaries/en/d.js
cat dictionary.js | awk '$1 ~ /^E/' >> dictionaries/en/e.js
cat dictionary.js | awk '$1 ~ /^F/' >> dictionaries/en/f.js
cat dictionary.js | awk '$1 ~ /^G/' >> dictionaries/en/g.js
cat dictionary.js | awk '$1 ~ /^H/' >> dictionaries/en/h.js
cat dictionary.js | awk '$1 ~ /^I/' >> dictionaries/en/i.js
cat dictionary.js | awk '$1 ~ /^J/' >> dictionaries/en/j.js
cat dictionary.js | awk '$1 ~ /^K/' >> dictionaries/en/k.js
cat dictionary.js | awk '$1 ~ /^L/' >> dictionaries/en/l.js
cat dictionary.js | awk '$1 ~ /^M/' >> dictionaries/en/m.js
cat dictionary.js | awk '$1 ~ /^N/' >> dictionaries/en/n.js
cat dictionary.js | awk '$1 ~ /^O/' >> dictionaries/en/o.js
cat dictionary.js | awk '$1 ~ /^P/' >> dictionaries/en/p.js
cat dictionary.js | awk '$1 ~ /^Q/' >> dictionaries/en/q.js
cat dictionary.js | awk '$1 ~ /^R/' >> dictionaries/en/r.js
cat dictionary.js | awk '$1 ~ /^S/' >> dictionaries/en/s.js
cat dictionary.js | awk '$1 ~ /^T/' >> dictionaries/en/t.js
cat dictionary.js | awk '$1 ~ /^U/' >> dictionaries/en/u.js
cat dictionary.js | awk '$1 ~ /^V/' >> dictionaries/en/v.js
cat dictionary.js | awk '$1 ~ /^W/' >> dictionaries/en/w.js
cat dictionary.js | awk '$1 ~ /^X/' >> dictionaries/en/x.js
cat dictionary.js | awk '$1 ~ /^Y/' >> dictionaries/en/y.js
cat dictionary.js | awk '$1 ~ /^Z/' >> dictionaries/en/z.js