#!/usr/bin/env bash
cat dictionaries/en/a.js | awk '{ print "\"" $1 "\"," }' > dictionaries/wrapped/a.js
cat dictionaries/en/b.js | awk '{ print "\"" $1 "\"," }' > dictionaries/wrapped/b.js
cat dictionaries/en/c.js | awk '{ print "\"" $1 "\"," }' > dictionaries/wrapped/c.js
cat dictionaries/en/d.js | awk '{ print "\"" $1 "\"," }' > dictionaries/wrapped/d.js
cat dictionaries/en/e.js | awk '{ print "\"" $1 "\"," }' > dictionaries/wrapped/e.js
cat dictionaries/en/f.js | awk '{ print "\"" $1 "\"," }' > dictionaries/wrapped/f.js
cat dictionaries/en/g.js | awk '{ print "\"" $1 "\"," }' > dictionaries/wrapped/g.js
cat dictionaries/en/h.js | awk '{ print "\"" $1 "\"," }' > dictionaries/wrapped/h.js
cat dictionaries/en/i.js | awk '{ print "\"" $1 "\"," }' > dictionaries/wrapped/i.js
cat dictionaries/en/j.js | awk '{ print "\"" $1 "\"," }' > dictionaries/wrapped/j.js
cat dictionaries/en/k.js | awk '{ print "\"" $1 "\"," }' > dictionaries/wrapped/k.js
cat dictionaries/en/l.js | awk '{ print "\"" $1 "\"," }' > dictionaries/wrapped/l.js
cat dictionaries/en/m.js | awk '{ print "\"" $1 "\"," }' > dictionaries/wrapped/m.js
cat dictionaries/en/n.js | awk '{ print "\"" $1 "\"," }' > dictionaries/wrapped/n.js
cat dictionaries/en/o.js | awk '{ print "\"" $1 "\"," }' > dictionaries/wrapped/o.js
cat dictionaries/en/p.js | awk '{ print "\"" $1 "\"," }' > dictionaries/wrapped/p.js
cat dictionaries/en/q.js | awk '{ print "\"" $1 "\"," }' > dictionaries/wrapped/q.js
cat dictionaries/en/r.js | awk '{ print "\"" $1 "\"," }' > dictionaries/wrapped/r.js
cat dictionaries/en/s.js | awk '{ print "\"" $1 "\"," }' > dictionaries/wrapped/s.js
cat dictionaries/en/t.js | awk '{ print "\"" $1 "\"," }' > dictionaries/wrapped/t.js
cat dictionaries/en/u.js | awk '{ print "\"" $1 "\"," }' > dictionaries/wrapped/u.js
cat dictionaries/en/v.js | awk '{ print "\"" $1 "\"," }' > dictionaries/wrapped/v.js
cat dictionaries/en/w.js | awk '{ print "\"" $1 "\"," }' > dictionaries/wrapped/w.js
cat dictionaries/en/x.js | awk '{ print "\"" $1 "\"," }' > dictionaries/wrapped/x.js
cat dictionaries/en/y.js | awk '{ print "\"" $1 "\"," }' > dictionaries/wrapped/y.js
cat dictionaries/en/z.js | awk '{ print "\"" $1 "\"," }' > dictionaries/wrapped/z.js